### ISSUE TITLE
Crashes on empty builds

### ISSUE THREAD

**Issue by ismay** [johnotander/ember-cli-csslint#7]
When trying to lint an empty vendor.css:

> assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: line undefined, col undefined, Fatal error, cannot continue: Cannot read property 'getLine' of null
1 error

**Comment by johnotander** [comment]
Thanks for reporting this, I diagnosed it as an issue with [broccoli-csslint](https://github.com/johnotander/broccoli-csslint). So, I am currently adding a patch, and will then update this addon's dependency.

**Comment by johno** [comment]
Take `ember-cli-csslint@1.0.1` for a spin @ismay, hopefully that will fix the error. Let me know if there are any other problems. Thanks!

**Comment by ghost** [comment]
Ah yes, that's fixed it. Thanks for the quick reply!

**Comment by johno** [comment]
Not a problem, thanks again for reporting this! :smile_cat:
